### ISSUE TITLE
Fix code scanning alert - Incorrect conversion between integer types

### ISSUE THREAD

**Issue by mosajjal** [gopacket/gopacket#59]
Tracking issue for:
- [ ] https://github.com/gopacket/gopacket/security/code-scanning/3

**Comment by mosajjal** [comment]
Hi @thorsager do you reckon we need to change the offset in `setBaseLayer` function from `int` to `int64`?

**Comment by thorsager** [comment]
> Hi @thorsager do you reckon we need to change the offset in `setBaseLayer` function from `int` to `int64`?
I'm not entirely sure of the context, could I be allowed to have a look at https://github.com/gopacket/gopacket/security/code-scanning/3 ?

**Comment by thorsager** [comment]
Having looked a bit more closer on the `int` conversions happening in `setBaseLayer`. They are caused by the fact that `SIP.contentLength` is `int64` which is perhaps overkill as I believe the maximum allowed size of a sip-message is 65535  bytes. including UDP and IP headers.

**RFC3261 18.1.1 Sending requests**:
> ... However, implementations MUST be able to handle messages up to the maximum
> datagram packet size.  For UDP, this size is 65,535 bytes, including IP and UDP headers.

So if the issue is the `int64` to `int` conversion I guess the best we can do without changing the type of `SIP.contentLength` the best thing we can do is "guard" against values that would overflow an `int`.

_that being said, the consequences of an actual content-length containing a value larger than what can be contained in an `int` WOULD break stuff, so in that regard, actually rejecting such values when parsing headers would perhaps be good thing?_

**Comment by mosajjal** [comment]
#61 should fix this. closing for now
